server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8070
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter
        - id: authenticate
          uri: http://localhost:8085
          predicates:
            - Path=/authenticate/**

security:
  url: http://localhost:8085

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
